### PR TITLE
Adding 3 jacobi examples, and a stencil layout

### PR DESCRIPTION
**Pull request by ahonorat**
Changes on sycl:
- implementation of an omp case in parallel_for_workitem (one thread per workitem in a group);
- implementation of an omp barrier;
- a few corrections (syntax error $$) and adaptations (g++, DEBUG) in Makefile.

New test case (they all should print "Result: \ ok"):
- jacobi/jacobi2d, using classical parallel_for;
- jacobi/jacobi2d-tile, using hierarchical parallel_for (and simulation of local memory);
- jacobi/jacobi2d-stencil, using a stencil library based on sycl.

### CODE REVIEW

**Comment by keryell** [comment]
Amazing!
Can you split your work in smaller commits with one commit per logical feature?
Is it a pull request for the master branch (the final spec) or the SYCL-1.2-provisional-2 (the previous spec)?
If it is for the SYCL-1.2-provisional-2 I can merge it and we can adapt it later to the master branch.
Thank you.

**Comment by ahonorat** [comment]
Hi ! I have split into 5 commits. I didn't check the other branches: I did it in the master branch, and it works fine. If something changes in the future spec, I don't know what it would affect...

**Comment by keryell** [comment]
Great!

Yes it works but actually it is the old master branch which has been renamed SYCL-1.2-provisional-2 since the SYCL-1.2 has been publicly announced last Monday. So it is to be a PR for the SYCL-1.2-provisional-2 branch now. Sorry about this.

Could you configure your git to have your real name in the commit? You can do it afterwards with git filter-branch or other. I can do it if you want.

I saw that you have some test files in
include/constants.h
include/stencil.hpp
I prefer to keep include/ for the general include directory to be installed.
So perhaps it would be cleaner to have these files into
tests/include
or
tests/jacobi/include
according to the generality of these files.

I have to think further about your use of #pragma omp barrier
Are you sure it does what you expect?
It does not have the same semantics as a "GPU" barrier.
A cleaner way to write it is to replace it by 2 consecutive parallel_for_workitem(), I think.

Thanks!

**Comment by ahonorat** [comment]
Hi ! 

I moved the .h in tests/include and I've changed the name in the commits.

Besides I've been thinking a lot about your remark on the barrier ... and yes I could have used 2 consecutive parallel_for_workitem (I like the Shadok ...).

Originally we wanted to use a local accessor, but it's not implemented and I'm not sure that regarding to the spec the local accessor is not flushed between two consecutive parallel_for_workitem. So in order to have shared memory in a workgroup I used the hierarchical parallel_for with a static array declaration in it. I wasn't sure of the result so I look into the code, and I code a badly parallel version of the parallel_for_workitem, although this is not necessary.

So now, I don't really understand what is the purpose of the (at least local) barrier if we always can put several consecutive parallel_for_workitem. Have you a simple example where it is useful ?  

Regards

**Comment by keryell** [comment]
The code looks fine now and it is running on my computer.
Could you edit your pull-request so that it is for the SYCL-1.2-provisional-2 branch? I cannot change it myself.
For your MIN/MAX issue, in C++14 `std::min`/`std::max` are now `constexpr`, so you should not need to use a macro anymore when working on template parameters. :-)

The purpose of the barrier is to provide a way to program in the genuine OpenCL style. But it is equivalent to use hierarchical parallelism, which is the more modern way and is also efficient on a CPU. Implementing the old-school OpenCL barrier on CPU without compiler support requires some atrocities such as 1 `setjump()`/`longjump()` per work-item. I planned to implement this in the future with Boost.Context or Boost.Coroutine, to be portable. I hope it will not choke OpenMP implementations... But actually your solution using just OpenMP nested parallelism to have 1 thread per work-item is definitely quite simpler and I love this! :-) Let's do OpenMP deal with this. But of course, if there is no OpenMP support, the barrier will not work and the user code will fail. So a requirement for triSYCL may be to have an OpenMP implementation supporting nested parallelism.
In the future you will be able to simplify your code by using a
`#pragma omp parallel for num_thread(...) collapse (1/2/3)`. But let's keep it like this since it is not on the critical path.

Thanks a lot!

**Pull request closed without merging**
